"""add_api_key_fields_and_teams

Revision ID: 5731f53bce58
Revises: add_production_indexes
Create Date: 2026-04-16 05:20:27.781337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5731f53bce58'
down_revision: Union[str, None] = 'add_production_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted to keep prod indexes ###
    op.drop_table('query_counts')
    op.add_column('billing_events', sa.Column('razorpay_event_id', sa.String(length=255), nullable=True))
    op.add_column('billing_events', sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True))
    op.add_column('billing_events', sa.Column('razorpay_order_id', sa.String(length=255), nullable=True))
    op.drop_constraint('billing_events_stripe_event_id_key', 'billing_events', type_='unique')
    op.create_unique_constraint(None, 'billing_events', ['razorpay_event_id'])
    op.drop_column('billing_events', 'stripe_event_id')
    op.drop_column('billing_events', 'stripe_subscription_id')
    op.drop_column('billing_events', 'stripe_invoice_id')
    
    op.add_column('users', sa.Column('api_key_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('api_key_created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted to keep prod indexes ###
    op.drop_column('users', 'api_key_created_at')
    op.drop_column('users', 'api_key_name')
    
    op.add_column('billing_events', sa.Column('stripe_invoice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('billing_events', sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('billing_events', sa.Column('stripe_event_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'billing_events', type_='unique')
    op.create_unique_constraint('billing_events_stripe_event_id_key', 'billing_events', ['stripe_event_id'])
    op.drop_column('billing_events', 'razorpay_order_id')
    op.drop_column('billing_events', 'razorpay_payment_id')
    op.drop_column('billing_events', 'razorpay_event_id')
    
    op.create_table('query_counts',
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('period', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='query_counts_pkey')
    )
    # ### end Alembic commands ###
